### ISSUE TITLE
Markdown export in sieben-manage

### ISSUE THREAD

**Issue by ahitrin** [ahitrin/SiebenApp#311]
Sometimes it would be helpful to export a goaltree from Sieben database to an external system that support nothing more than formatted text (a kind of wiki or GitHub). The most popular structured plain text format nowadays is Markdown.

So, let's implement a markdown export in `sieben-manage`. It should work like existing `sieben-manage dot`, with new enhancements planned to implement in #310.

**Comment by ahitrin** [comment]
Expected format:

```markdown
* [ ] **11** Root
  * [x] **12** Some (blocked by **13**, **14**)
  * [x] **13** Another
    * [x] **14** Nested
  * [ ] **15** Next
```

This should produce the following result:

* [ ] **11** Root
  * [x] **12** Some (blocked by **13**, **14**)
  * [x] **13** Another
    * [x] **14** Nested
  * [ ] **15** Next

**Comment by ahitrin** [comment]
Or:

```markdown
Root (**11**, open):
* [x] **12** Some (blocked by **13**, **14**)
* [x] **13** Another
  * [x] **14** Nested
* [ ] **15** Next
```

With the following rendering result:

---

Root (**11**, open):
* [x] **12** Some (blocked by **13**, **14**)
* [x] **13** Another
  * [x] **14** Nested
* [ ] **15** Next

**Comment by ahitrin** [comment]
Finished. An example: full goaltree for version 0.11 exported into Markdown with `sieben-manage md -np sieben.db`:

---

* [ ] **-1** [0/1] SiebenApp (blocked by **21**)
* [x] **11** [1/1] Allow only one parent goal (but many blocked ones) #16
* [x] **13** [1/1] Add new layer for autolink #181
* [x] **16** [1/1] Stabilize properties tests with enabled autolink #181
* [x] **18** [1/1] Zoom: disallow to zoom on out-of-tree goal
* [ ] **21** [30/48] [Version 0.11]
  * [x] **12** [1/1] Markdown export in sieben-manage #311
  * [ ] **14** [0/1] Code cleanup: remove usage of Goals private methods in AutoLink.accept_ToggleAutoLink #181
  * [x] **15** [4/4] Consider layers in 'sieben-manage dot' #310
    * [x] **31** [2/2] Add tests on existing 'sieben-manage' behavior #310
      * [x] **32** [1/1] Move all 'sieben-manage' code into 'siebenapp/manage.py' #310
    * [x] **33** [1/1] sieben-manage: define layer usage rules in adoc #310 -- use flags only fore views
  * [ ] **17** [0/1] Review and cleanup zoom tests #181
  * [ ] **19** [20/26] Replace dict in q() with a dataclass #329
    * [x] **38** [1/1] Make possible to return all values from rows #329
    * [x] **39** [1/1] Add type annotations for RenderResult.slice()? -- no, remove it at all #329
    * [ ] **42** [15/18] Get rid of legacy RenderResult.graph #329
      * [x] **55** [1/1] Use RenderRows in test_database.py
      * [x] **56** [1/1] Use RenderRows in test_properties
      * [x] **58** [1/1] Use RenderRows in sieben_dpg #329
      * [x] **59** [1/1] Use RenderRows in app.py #329
      * [ ] **50** [0/2] Use RenderRows in render.py #329
        * [ ] **62** [0/1] Decide how to manage additional properties ('x', 'y', 'col', 'row') added during rendering process #329
      * [x] **61** [11/11] Use RenderRows in manage.py #329
        * [x] **41** [10/10] Use RenderRows in all layers #329
          * [x] **30** [1/1] Add tests for combining rows and graph in RenderResult? -- no need to do it #329
          * [x] **44** [1/1] Use RenderRows in Enumeration #329
          * [x] **45** [1/1] Use RenderRows in FilterView #329
          * [x] **46** [1/1] Use RenderRows in SwitchableView #329
          * [x] **47** [1/1] Use RenderRows in OpenView #329
          * [x] **48** [1/1] Use RenderRows in ProgressView #329
          * [x] **49** [1/1] Use RenderRows in Zoom #329
          * [x] **40** [1/1] Use RenderRows in AutoLink #329
          * [x] **51** [1/1] Use RenderRows in Goals #329
    * [ ] **52** [2/4] Use selection field into RenderResult #329
      * [ ] **53** [0/1] Add selection dict into RenderResult and still use RenderRow.select field #329
      * [x] **54** [2/2] Use RenderResult in all tests instead of .rows (mass refactoring with comby) #329
        * [x] **57** [1/1] Transform RenderResult into dataclass #329
    * [x] **63** [1/1] Add new test into test_open_view that use zoom #329
  * [ ] **10** [0/1] Sieben-manage: merge database files #179
  * [ ] **25** [0/1] ADR: define a feature limit, connect to "forever alpha version" ADR
  * [ ] **27** [0/2] AutoLink: add parent link, not blocker #181
    * [ ] **28** [0/1] AutoLink: add a test on multiple additions #181
  * [ ] **29** [5/8] 0.11 code cleanup
    * [ ] **22** [1/3] Graph.verify: split into little verifiers
      * [ ] **23** [0/1] Graph.verify: use getattr() to find all little _verify_XX methods and run them
      * [x] **24** [1/1] Graph.verify: do not return boolean (it's unused)
    * [x] **35** [1/1] Cleanup: move dot functions from system to manage module
    * [x] **36** [1/1] Cleanup: move md functions from system to manage module
    * [x] **43** [2/2] Try to use approvaltests-minimal 5.3.3 instead of approvaltests 5.6.0+
      * [x] **20** [1/1] Try to use approvaltests-minimal instead of approvaltests -- do not work in 5.3.3
  * [ ] **34** [0/2] Progress layer: use separate 'prefix' field instead of 'name' to show progress
    * [ ] **37** [0/1] Goaltree: use new field that's attached to 'name' on display but is always empty by default (blocked by **19**)
* [x] **26** [1/1] Blog: release 0.10
